### ISSUE TITLE
Functionality of MF_DETECTION

### ISSUE THREAD

**Issue by ghost** [iceman1001/ChameleonMini-rebooted#25]
What is the functionality of the MF_DETECTION configuration?

What should be happen if a slot is configured in detection mode?

Thanks a lot.

**Comment by iceman1001** [comment]
It saves the reader / card authentication sequence and it is used later to run mfkey32 with, in order to get the key used.

**The process**
Basically,  you set MF_DETECTION,    you present device to a genuine reader and wait for awhile.
Then you reconnect device to computer and press 

- **mfkey**  (in new GUI)  
- **fast calc**  (in old GUI)

and if you are lucky,  some keys are found and printed in textbox..

**Comment by ghost** [comment]
Thanks a lot.

You think it is possible to add this functionality to a RevG too?
I like my rebooted device, but RevG has, reader, sniffer, ... that I don't want to miss.
Anyone has ideas which files depending on mf_detection?

- /Application/Detection.c
- /Application/Detection.h
- /Application/Application.h
- /Terminal/Commands.c
- /Terminal/Commands.h
- configuration.c
- configuration.h

Special things to care about?

**Comment by kevin2008-01** [comment]
But for working, you need one valid UID for the reader.

**Comment by iceman1001** [comment]
Of course its possible,  everything you need you have. 
You still would need the GUI to do the cracking part,  or you need to implement the mfkey32 attack into the commandline part.

Just understand what you need to execute it.

**Comment by iceman1001** [comment]
closing since its a question for RevG - repo.

**Comment by ghost** [comment]
@iceman1001 thanks I understood.
I'll go on for it. 
Cheers
