### ISSUE TITLE
Getting ChameleonMini in DFU Mode

### ISSUE THREAD

**Issue by ghost** [iceman1001/ChameleonMini-rebooted#52]
According to the documentation, I should be able to get the ChameleonMini into DFU mode by holding the black button while plugging it in. However, this is not working. I put the Chameleon into Sniffing Mode, and now it's not detected as an USB device anymore, and I need to reflash it somehow. Shorting PC3 and GND also does not work, maybe I'm doing the button press wrong?

**Comment by slurdge** [comment]
I have the same problem, I believe some units don't behave properly.

**Comment by NKT00** [comment]
I've just got one, and, well, which one even *is* the "right button"? One is red and one is black, mounted vertically, and the text is horizontal with the coil to the right.
So far it's thrown an error under Windows 10, which says it is a malfunctioning USB device, and under Ubuntu it doesn't do anything at all. 
Anyone got any ideas?

**Comment by bogiton** [comment]
@pitikay What exactly is the "Sniffing Mode"? Chameleon RevE rebooted doesn't support reading/sniffing by design. In any case, there are two ways to enter the bootloader mode, either use the GUI or you keep the black button pressed while plugging in the usb cable.

@NKT00 Is the "right button" mentioned somewhere in the Wiki? As far as I can see, it is only referenced as "black button". Red button should speak for itself that is the power button. There are many references in the Wiki and other issues with solutions to non-detectable or bricked devices.

**Comment by iceman1001** [comment]
I wonder which revision of Chameleon they are using...  Sounds like RevG

**Comment by bogiton** [comment]
@iceman1001 Most likely :P

**Comment by ghost** [comment]
@iceman1001 not really- RevG doesn’t have colored buttons ;)
@pitikay @NKT00 Can someone upload a picture from your device?

**Comment by iceman1001** [comment]
A **RevE rebooted** device has RED and BLACK buttons.  So their devices seem to be Rev E Rebooted.

Which firmware has sniffing mode?   Not RevE rebooted at least. 
_Shorting PC3 and GND _   ??  @bogiton  's first post says it all.

**Comment by ghost** [comment]
right :) skipped it

**Comment by ghost** [comment]
Thank you all for the replies, I attached a picture of my device - it's a chinese RevE Rebooted.
![ex_19-01-28 08-50-00 7243](https://user-images.githubusercontent.com/9059104/51822089-80776000-22db-11e9-8f5f-d67c9414010c.jpg)

@bogiton There was a flag in the firmware for that specific mode, and well, I guess I played with it too much, without knowing what it'd do. Figured I could always boot it into DFU mode, but since it isn't detected by Windows or various distros anymore, and the button hold technique also doesn't work, I guess I'm out of luck with this one :)

**Comment by slurdge** [comment]
@pitikay You have the same device as me. You can almost always salvage it by reprogramming it through the 4 little pins on the left of you CR2032 holder. You would need a special device though (or you can reprogram a small MCU to act as a debugger).

I had the same situation as you but it could be saved in the end.

**Comment by iceman1001** [comment]
JTAG it...   thats the option that always work :)

**Comment by securechicken** [comment]
@pitikay did you try to flash the original bootloader with original Windows flashing binary to the device, so that it becomes a dumb flashable brick you can upgrade with a new (working) firmware again?
As described in [here](https://github.com/iceman1001/ChameleonMini-rebooted/wiki/Getting-started#no-more-light-go-back-to-stock).

I then guess this issue could be closed @iceman1001 .

**Comment by iceman1001** [comment]
Closed because of inactivity
