### ISSUE TITLE
Problem to use/handle the Chameleon mini RevE Rebooted

### ISSUE THREAD

**Issue by peseta3** [iceman1001/ChameleonMini-rebooted#61]
Hallo Together,
@iceman1001 

last Year I get an Chameleon Mini RevE Rebooted from Lab401.com
I had so my Problems with this.
[(https://github.com/iceman1001/ChameleonMini-rebooted/issues/9)](url)

Now I want to try it again and hope it will now work.
I use Windows10 and use some GUI`s, the old from last Year with calc/fast calc Bottum, from Iceman, from LAB401and TeraTerm.

Windows DeviceManager:  Anschlüsse(COM&LPT)---Serielles USB-Gerät (COM3)

![usb chameleon](https://user-images.githubusercontent.com/24300824/49642433-4abca600-fa13-11e8-90c0-79fe3a28e4d5.jpg)

They all say`s that it is connected.
The firmeware is Chameleon-new-1.0

![usb chameleon1](https://user-images.githubusercontent.com/24300824/49642554-adae3d00-fa13-11e8-958d-ce4c9763f5cd.jpg)

![usb chameleon2](https://user-images.githubusercontent.com/24300824/49642611-df270880-fa13-11e8-8f13-cbe2bf08a345.jpg)

Is this the correct Firmware?

I want to snif a Cardreader ACR122u with the Chameleon, but nothing happens.
I think normaly the Chameleon LED should be blinking shortly, but the LED is on th hole time if I but it on the Cardreader.
I use a battery from Chameleon too.
Before I use it I connected with a PC Windows10 with GUI.
Firmware is Chameleon-new-1.0
Slot1   MF_DETECTION  SWITCHCARD  APPLY  SET ACTIVE

I use this viedeo for Tutorial
[https://lab401.com/blogs/academy/chameleon-mini-mifare-cracking-via-the-reader-attack](url)

Are you  any Ideas? Whats wrong?

**Comment by peseta3** [comment]
No one any Idea?
If I use the GUI the serial Part, and I type  RSSIMY?
I get this:


`--> RSSIMY?
101:OK WITH TEXT
    0 mV`


Is it normal, if I have a Tag/ Mifare_1k near the Chameleon?

Sometimes I think the Chameleon/Reader doesn`t work. Maybee it is out of Order?

**Comment by iceman1001** [comment]
the chameleon-new-1.0 firmware string is a sign your firmware is of the  RevE rebooted which as a side note  has changed since we got it open-sourced again.

One of the eight slot leds should be on, indicating which slot you are currently using.
If you download latest GUI,  you will see it clearly marked with green borders.

The obvious question is if you have configed the active slot correct. So that it has something to answer your ACR122u reader when it issues a command to your chameleon.   I don't know how you are control your aCR122u, since you didn't say  but I assume you have some software where you can tell it to identify tag.

**Comment by peseta3** [comment]
Ah Hello Iceman,
thank you for your answere.
The ACR122u reader use the original ACR122U Windows Software.
And the output is the correct Data from Slot 1.
But how can I use The Chameleon stand allown to pick up Data from Card or Reader?
And use them with PC and USB Cabel as a Reader?
I didn`t get any Data from e.g. Mifare classik 1k.

**Comment by iceman1001** [comment]
I think you have missunderstood the chameleon device.   It can simulate a tag, meaning you need to upload a tag memory dump onto a tag slot.   Ie,  1k mifare classic dump.

Then you present the chameleon to the reader,  which can do stuff.  
Then you hook up the chameleon with the GUI, to download the memory again.

You can now analyse what the reader did to the card.
You can also use the mode  MF_DETECT,  and present to a reader,  which tries to authenticate to the chameleon.   afterwards, you hook up the chameleon to the device and run "mfkey32 attack",  in order to potentially get the key out from those reader authentication attempts.

The chameleon doesn't need a cable,  it can run on the battery.  You only need to hook up the cable when you want to communicate with it using the GUI.

**Comment by peseta3** [comment]
ah, yes I understand.
 but with this

> You can now analyse what the reader did to the card.
You can also use the mode MF_DETECT, and present to a reader, which tries to authenticate to the chameleon. afterwards, you hook up the chameleon to the device and run "mfkey32 attack", in order to potentially get the key out from those reader authentication attempts.

I want to try this, but it doesn`t work.
I think Slot 1 LED should be blink if I put it to the ACR122u.
But the LED is only on the hole Time.
And if I make mfkey32 Attack. I get.

`mfkey32 attack failed, no keys found`

**Comment by iceman1001** [comment]
What do you do with the ACR122u?   Do you tell it to authenticate against the card (chameleon)?

**Comment by peseta3** [comment]
With the ACR122u, I do nothing, he is only conected with USB and the Software.
He is in read modus, to read all cards and coneced them or not.

**Comment by iceman1001** [comment]
...but what does the  ACR122u reader read?   only uid?   or does it try to read the whole memory from card?

**Comment by peseta3** [comment]
If i click on read "get data" he read the UID.
If I put only the card on the reader the green led is on. and he accept the card

**Comment by iceman1001** [comment]
So the chameleon works and this is not a firmware issue.

Somewhere in you AC122u software, you will need to tell it which keys to use etc in order to be able to authenticate against the card.  Without it,  it can't read the memory.

**Comment by peseta3** [comment]
Yes sure you are right thats not an Firmware Issue, with your Work is all ok and great.

ok I understand.
But how is it to use the Chameleon as reader and Read a Card Standalone?
Can you tell me about this a little bit.
Yes I know its not your Problem, but I have the Chameleon one Year an I can not realy work with them without some Informations for it. I read realy many of Documents, but nothing about handling it.

**Comment by iceman1001** [comment]
The Chameleon RevE rebooted can not act as reader.   It can not read cards. 

If you have a Chameleon RevG  it can act as reader if you upload latest firmware.

**Comment by peseta3** [comment]
Hmm 
but Lab401 wrote me that he can Read

> The device has specific read modes, and can also be written to.

But he should be comunicate with the e.g. Door acces reader, I saw it in the Video from LAB401.

**Comment by iceman1001** [comment]
Well,  if LAB401 knows better than me,  then I stand corrected.   I can't get my RevE rebooted device to read cards.
The chameleon on the video you refer to is in slot1 MF_DETECTION mode,   it doesn't read cards.
The door tries to authenticate against it,   using the gui, it can crack the key which was use by the door reader.  Then the video goes on showing how to crack the rest of the card (meaning you have the card to the door).    Nowhere in that video does it show the chameleon acting as a reader and reads cards.

This issue is closing,
